name: lapalma-earthquakes
channels:
  - conda-forge
  - default
dependencies:
  - jupyterlab>=4.0
  - numpy
  - matplotlib
  - pandas
  - scipy
  - seaborn
  - altair
  - plotly
  - pip
  - pip:
    - jupyterlab-quarto
